Get sign of an instruction
sbip-sg/llvm-project pull request #14
Opened 2022-07-19 07:08 UTC by thanhtoantnt

# Description
C binding to get a sign of an instruction

In process of fixing https://github.com/sbip-sg/verazt/issues/85

# How Has This PR Been Tested?

Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration.

- The binding is tested with the input files from benchmarks of [discover](https://github.com/sbip-sg/verazt )

# Checklist:

Please ensure that all items are reviewed and checked by the notation: `[x]`.
(The irrelevant items can be stricken through by the notation: `~~ ... ~~`, but
they still need to be checked.)

- [x] Self-review: I have reviewed my code thoroughly before creating the PR.
- [x] Code linting: I have run `clang-format` with relevant files.

2022-07-19 12:27 UTC, taquangtrung requested changes

2022-07-19 12:27 UTC, taquangtrung commented on llvm/lib/IR/Core.cpp
> +
Remove this  empty line?

2022-07-19 12:27 UTC, taquangtrung commented on llvm/lib/IR/Core.cpp
> +
Remove this empty line?

2022-07-19 12:27 UTC, taquangtrung commented on llvm/lib/IR/Core.cpp
> +  DbgDeclareInst* dbg_declare_inst = dyn_cast<DbgDeclareInst>(unwrap(Inst));
The naming style of variable names in this function isn't consistent with other functions in this file.
@thanhtoantnt: can you refactor the code?

2022-07-19 12:32 UTC, taquangtrung requested changes

2022-07-19 12:32 UTC, taquangtrung commented on llvm/lib/IR/Core.cpp
> +int LLVMGetSignInfo(LLVMValueRef Inst){
Rename function to `LLVMGetSignednessInfo`

2022-07-19 15:43 UTC, thanhtoantnt commented
@taquangtrung I refactored the code to resolve your comments.

2022-07-19 15:47 UTC, taquangtrung requested changes

2022-07-19 15:47 UTC, taquangtrung commented on llvm/include/llvm-c/Core.h
> +                          macro(GetElementPtrInst) macro(InsertElementInst) macro(                  \
`Clangformat` seems to break all default formatting of the old code base?

@thanhtoantnt: can you investigate how to run Clangformat but still preserve the existing code structure?

If this is not possible, then we may need to formatting the code manually.

2022-07-19 15:48 UTC, taquangtrung commented on llvm/include/llvm-c/Core.h
> +                          macro(GetElementPtrInst) macro(InsertElementInst) macro(                  \
@thanhtoantnt: maybe this can help: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

2022-07-20 02:10 UTC, thanhtoantnt commented
@taquangtrung Now, only new code is formatted using `clang-format`, other parts are kept intact.

2022-07-20 12:23 UTC, taquangtrung approved these changes

2022-07-20 12:24 UTC, merged

2022-07-20 12:32 UTC, taquangtrung commented
Merged! Thanks @thanhtoantnt!