Get variable in a llvm.dbg.declare instruction
sbip-sg/llvm-project pull request #15
Opened 2022-07-21 06:56 UTC by thanhtoantnt

# Description

This function is to get varialbe of a `llvm.dbg.declare`
For example: if the input is `call void @llvm.dbg.declare(metadata i16* %1, metadata !14, metadata !DIExpression()), !dbg !16`, this function will output `%1`.

In part to fix https://github.com/sbip-sg/verazt/issues/87

# How Has This PR Been Tested?

Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration.

- Cases in `benchmarks/c-c++/sv-comp/Juliet-Test-Suite-V1.3/CWE197_Numeric_Truncation_Error`  benchmark with the `numeric-truncation` of `verazt`.

# Checklist:

Please ensure that all items are reviewed and checked by the notation: `[x]`.
(The irrelevant items can be stricken through by the notation: `~~ ... ~~`, but
they still need to be checked.)

- [x] Self-review: I have reviewed my code thoroughly before creating the PR.
- [x] Code formatting: I have run `clang-format` with relevant code.
- [x] Comments: I have commented on the hard-to-understand areas in my code.
- [x] Documentation: I have updated new changes to the documentation.
- ~~[ ] Unit-tests: I have added the necessary unit tests.~~

2022-07-22 16:03 UTC, taquangtrung requested changes

2022-07-22 16:03 UTC, taquangtrung commented on llvm/lib/IR/Core.cpp
> +/*-- Get the variable in the llvm.dbg.declare instructions .................--*/
Maybe we need to add a note in the documentation to indicate that this function is a customized version of SBIP?

Something like this: 

https://github.com/sbip-sg/llvm-project/blob/ec52fbac6b8f148a9663224cc4e20f3482a13701/llvm/lib/Analysis/Analysis.cpp#L164-L165

2022-07-22 16:03 UTC, taquangtrung commented on llvm/lib/IR/Core.cpp
> +LLVMValueRef LLVMGetDbgDeclareVar(LLVMValueRef Inst) {
Also, can this function be grouped with `LLVMGetSignednessInfo` in the same category: 

``` c
/*--.. Get data from debugging information ........................................--*/
```

or something similar?

2022-07-22 16:05 UTC, taquangtrung commented
@thanhtoantnt: I noticed the new binary released is quite large (1GB). My releases take only 600MB for each release.

https://github.com/sbip-sg/llvm-project/releases

Can you reduce the release size?

2022-07-25 04:03 UTC, thanhtoantnt commented
@taquangtrung I added documentation to resolve your comment. About the size of the release file, we can discuss in #6.

2022-07-25 05:33 UTC, taquangtrung approved these changes

2022-07-25 05:34 UTC, merged